Repository MaiQuocHuy/nextjs-course-project, pull requests merged in 2025-09, with the labels that each got.

#92 Update instructor's enrolled student detail page
  src/components/dashboard-student/quiz-results/QuizResultDetailsDialog.tsx
  src/components/instructor/course/CoursesPage.tsx
  src/components/instructor/course/CoursesSkeleton.tsx
  src/components/instructor/course/create-course/create-basic-infor/CreateCourseBasicInforPage.tsx
  src/components/instructor/students/EnrolledStudentList.tsx
  src/components/instructor/students/StudentsPage.tsx
  src/components/instructor/students/student-detail/StudentDetailsPage.tsx
  src/components/instructor/students/student-detail/StudentInfo.tsx
  src/services/instructor/courses/courses-api.ts
  src/services/instructor/students/students-ins-api.ts
  src/types/instructor/courses.ts
  src/types/instructor/students.ts
Labels: Review effort 3/5

#96 feat: implement Real-time Chat
  pnpm-lock.yaml
  src/app/(dashboard)/(instructor)/instructor/layout.tsx
  src/app/(dashboard)/(instructor)/instructor/websocket-test/page.tsx
  src/app/(nondashboard)/websocket-test/page.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatBubble.tsx
  src/components/chat/ChatComponent.tsx
  src/components/chat/ChatPanel.tsx
  src/components/chat/InstructorChatBubble.tsx
  src/components/chat/InstructorChatPanel.tsx
  src/components/chat/index.ts
  src/components/dashboard-student/DashboardLayout.tsx
  src/components/dashboard-student/learning/LearningContent.tsx
  src/components/dashboard-student/learning/LearningPageClient.tsx
  src/hooks/useChatInfiniteScroll.ts
  src/hooks/useChatWebSocket.ts
  src/hooks/useInfiniteScroll.ts
  src/services/instructor/courses/courses-api.ts
  src/services/student/studentApi.ts
  src/services/websocket/chatApi.ts
  src/services/websocket/chatWebSocketManager.ts
  src/services/websocket/index.ts
  src/services/websocket/webSocketService.ts
  src/store/store.ts
  src/types/chat.ts
  src/utils/student/index.tsx
Labels: Possible security concern, Review effort 4/5

#104 feat: Implement Affiliate Payout and Discount Usage pages for Instructor and Enhance UI
  pnpm-lock.yaml
  src/app/(dashboard)/(instructor)/instructor/affiliate-payout/[id]/page.tsx
  src/app/(dashboard)/(instructor)/instructor/affiliate-payout/page.tsx
  src/app/(dashboard)/(instructor)/instructor/discount-usage/[id]/page.tsx
  src/app/(dashboard)/(instructor)/instructor/discount-usage/page.tsx
  src/app/(dashboard)/(student)/dashboard/certificates/page.tsx
  src/app/(dashboard)/(student)/dashboard/page.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatHeader.tsx
  src/components/chat/ChatMessageItem.tsx
  src/components/chat/EmojiPicker.tsx
  src/components/chat/FileMessage.tsx
  src/components/chat/MessageActions.tsx
  src/components/common/CertificateDetailModal.tsx
  src/components/dashboard-student/CertificatesSummary.tsx
  src/components/dashboard-student/DashboardHeader.tsx
  src/components/dashboard-student/Sidebar.tsx
  src/components/dashboard-student/affiliate-payout/AffiliatePayoutMobileCard.tsx
  src/components/dashboard-student/affiliate-payout/AffiliatePayoutTable.tsx
  src/components/dashboard-student/affiliate-payout/AffiliatePayoutTableRow.tsx
  src/components/dashboard-student/certificates/CertificateMobileCard.tsx
  src/components/dashboard-student/certificates/CertificateRow.tsx
  src/components/dashboard-student/certificates/CertificatesClient.tsx
  src/components/dashboard-student/certificates/CertificatesHeader.tsx
  src/components/dashboard-student/certificates/CertificatesTable.tsx
  src/components/dashboard-student/certificates/index.ts
  src/components/dashboard-student/discount-usage/DiscountUsageMobileCard.tsx
  src/components/dashboard-student/discount-usage/DiscountUsageTable.tsx
  src/components/dashboard-student/discount-usage/DiscountUsageTableRow.tsx
  src/components/dashboard-student/ui/Loading.tsx
  src/components/dashboard-student/ui/LoadingError.tsx
  src/components/instructor/affiliate-payout/AffiliatePayoutDetailPage.tsx
  src/components/instructor/affiliate-payout/AffiliatePayoutPage.tsx
  src/components/instructor/affiliate-payout/AffiliatePayoutRow.tsx
  src/components/instructor/affiliate-payout/AffiliatePayoutTable.tsx
  src/components/instructor/affiliate-payout/index.ts
  src/components/instructor/affiliate-payout/shared/FilterBar.tsx
  src/components/instructor/affiliate-payout/shared/SearchBar.tsx
  src/components/instructor/affiliate-payout/shared/index.ts
  src/components/instructor/discount-usage/DiscountUsageDetailPage.tsx
  src/components/instructor/discount-usage/DiscountUsagePage.tsx
  src/components/instructor/discount-usage/DiscountUsageRow.tsx
  src/components/instructor/discount-usage/DiscountUsageTable.tsx
  src/components/instructor/discount-usage/index.ts
  src/components/instructor/discount-usage/shared/FilterBar.tsx
  src/components/instructor/discount-usage/shared/SearchBar.tsx
  src/components/instructor/discount-usage/shared/index.ts
  src/components/instructor/layout/InstructorSidebar.tsx
  src/services/instructor/affiliate-payout/affiliate-payout-api.ts
  src/services/instructor/discount-usage/discount-usage-api.ts
  src/store/store.ts
  src/types/instructor/affiliate-payout.ts
  src/types/instructor/discount-usage.ts
  src/types/student/index.ts
  src/utils/instructor/affiliate-payout/index.ts
  src/utils/instructor/discount-usage/index.ts
  src/utils/student/index.tsx
Labels: Possible security concern, Review effort 3/5

#106 feat: Fetch APIs to get Dashboard data
  src/components/chat/Chat.tsx
  src/components/dashboard-student/ActivityFeed.tsx
  src/components/dashboard-student/DashboardHeader.tsx
  src/components/dashboard-student/DashboardStats.tsx
  src/components/dashboard-student/EnrolledCoursesSummary.tsx
  src/components/dashboard-student/learning/LearningPageClient.tsx
  src/components/dashboard-student/ui/Loading.tsx
  src/hooks/student/useEmojiUtils.ts
  src/hooks/student/useFileUpload.ts
  src/hooks/student/useInfiniteScroll.ts
  src/hooks/student/useSection.ts
  src/services/student/studentApi.ts
  src/types/student/index.ts
  src/utils/student/index.tsx
Labels: Review effort 3/5

#107 feat: Done notification fearture
  src/components/common/NotificationTrigger.tsx
  src/components/common/NotificationsModal.tsx
  src/components/dashboard-student/DashboardHeader.tsx
  src/components/instructor/layout/InstructorHeader.tsx
  src/components/instructor/layout/InstructorSidebar.tsx
  src/components/ui/dialog.tsx
  src/services/notificationApi.ts
  src/store/store.ts
  src/types/index.ts
  src/types/notification.ts
Labels: Review effort 3/5

#108 Refactor coursesApi to use fetchBaseQuery and update base URL configuration
  src/services/coursesApi.ts
Labels: Possible security concern, Review effort 2/5

#113 Refactor: Adjust UI for Student Dashboard
  src/app/(dashboard)/(student)/dashboard/my-courses/page.tsx
  src/components/common/CertificateDetailModal.tsx
  src/components/dashboard-student/EnrolledCoursesSummary.tsx
  src/components/dashboard-student/affiliate-payout/AffiliatePayoutTableRow.tsx
  src/components/dashboard-student/courses/CourseCard.tsx
  src/components/dashboard-student/courses/CourseList.tsx
  src/components/dashboard-student/discount-usage/DiscountUsageTableRow.tsx
  src/components/dashboard-student/reviews/DeleteReviewAlert.tsx
  src/components/dashboard-student/reviews/EditReviewDialog.tsx
  src/components/dashboard-student/reviews/ReviewItem.tsx
Labels: Review effort 2/5

#115 fix bugs, increase UI/UX
  .env.example
  docs/CONTACT_FORM_GUIDE.md
  package-lock.json
  package.json
  src/app/(nondashboard)/certificates/page.tsx
  src/app/(nondashboard)/courses/[slug]/page.tsx
  src/app/(nondashboard)/courses/page.tsx
  src/app/(nondashboard)/privacy/page.tsx
  src/app/(nondashboard)/terms/page.tsx
  src/app/api/contact/route.ts
  src/app/data/contact.ts
  src/components/common/CourseCard.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/course-detail/CourseContent.tsx
  src/components/course-detail/InstructorProfile.tsx
  src/components/course/CourseSidebar.tsx
  src/components/forms/ContactForm.tsx
  src/components/maps/InteractiveMap.tsx
  src/components/sections/ContactInfoSection.tsx
  src/components/sections/HeroSection.tsx
  src/hooks/useCourses.ts
  src/lib/email.ts
  src/middleware.ts
  src/services/coursesApi.ts
  src/services/paymentApi.ts
Labels: Possible security concern, Review effort 4/5
